spring.application.name=parcelgo-backend

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/parcelgo}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:REMOVED_SECRET}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
logging.level.com.parcelgo=INFO
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=true
spring.flyway.out-of-order=true
spring.flyway.repair-on-migrate=false

jwt.secret=${JWT_SECRET:parcelgo-super-secret-key-change-in-production-min-256-bits}
jwt.expiration=${JWT_EXPIRATION:86400000}

spring.mail.host=${MAIL_HOST:smtp.gmail.com}
spring.mail.port=${MAIL_PORT:587}
spring.mail.username=${MAIL_USERNAME:smritiprajapati15@gmail.com}
spring.mail.password=${MAIL_PASSWORD:yhgwteooyrIcgemm}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.from=${MAIL_FROM:smritiprajapati15@gmail.com}
spring.jpa.open-in-view=true

twilio.account-sid=${TWILIO_ACCOUNT_SID:AC5fac3e649fc330b3bd89da1c2e3d7933}
twilio.auth-token=${TWILIO_AUTH_TOKEN:REMOVED_SECRET}
twilio.phone-number=${TWILIO_PHONE_NUMBER:+17372212163}

server.port=8081
